logging:
  config: classpath:config/logback-spring.xml

app:
  google:
    apikey: ENC(0Chd1VQ6Cj3bZRUOFA8bhrTXOKsKDmyzRdlCgdQQwhtL1RQ1OUYYt0hFEflSVZOO)
  citadel:
    apikey: ENC(Sk+2HpBSpMXd0XKkmPMHH/7EW9KgIKguCyOMrs+hsNTKyeBlqtD3hQHata2Z3Jxg)

---

spring:
  config:
    activate:
      on-profile: prod

app:
  citadel:
    url: http://localhost:8081
  discord:
    token: ENC(drdY9oR65OiBpOxQZbIi/5sffW06EB6Tv82NDMSNpqUYu/FmZOhN15ptxiLF7qxgRtAdJ291Tu4gYia/d/1C2MQliXIECPtK)

logging:
  level:
    com.neukrang.jybot: info

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: dev

app:
  citadel:
    url: http://localhost:8081
  discord:
    token: ENC(XiR7k2lUHae3OuZ1S1SX0KgZ7JfmI67ndN6oZ+nHy7J1EcR6O4JplxYHxnSl+W8KTwQCQH9nI0ZDq3eaOfoGZmQbd/ViyjRH)

logging:
  level:
    com.neukrang.jybot: debug

server:
  port: 8081

---