spring:
  profiles:
    active: local

server:
  port: 10283

logging:
  config: classpath:/config/logback-spring.xml
---
spring:
  profiles: local

app:
  citadel:
    url: http://localhost:8080

logging:
  level:
    com.neukrang.jybot: debug
---