logging:
  config: classpath:config/logback-spring.xml

---

spring:
  config:
    activate:
      on-profile: prod

app:
  citadel:
    url: http://localhost:8081

logging:
  level:
    com.neukrang.jybot: debug

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: dev

app:
  citadel:
    url: http://localhost:8081

logging:
  level:
    com.neukrang.jybot: debug

server:
  port: 8081

---